<a href="https://colab.research.google.com/github/GenAIUnplugged/machine-learning/blob/main/load_digits_dataset_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
from sklearn.datasets import load_digits
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split,GridSearchCV,RandomizedSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [ ]:
X,y = load_digits(return_X_y=True)

In [ ]:
X.shape,y.shape

((1797, 64), (1797,))

In [ ]:
type(X),type(y)

(numpy.ndarray, numpy.ndarray)

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((1437, 64), (360, 64), (1437,), (360,))

In [ ]:
def get_metrics(x_train,y_train,x_test,y_test,model_name,model):
    print(f"Model Name: {model_name}")
    model=model
    model.fit(x_train,y_train)
    y_pred = rf.predict(x_test)
    print("*"*50)
    print(f"Testing Score: {model.score(x_test,y_test)}")
    print(f"Training Score: {model.score(x_train,y_train)}")
    print(f"Accuracy Score: {accuracy_score(y_test,y_pred)}")
    print(classification_report(y_test,y_pred))
    print(confusion_matrix(y_test,y_pred))
    print("*"*50)

In [ ]:
rf = RandomForestClassifier(n_estimators=1000,random_state=42)
get_metrics(x_train,y_train,x_test,y_pred,"Random Forest",rf)

Model Name: Random Forest
**************************************************
Testing Score: 1.0
Training Score: 1.0
Accuracy Score: 1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        32
           1       1.00      1.00      1.00        29
           2       1.00      1.00      1.00        33
           3       1.00      1.00      1.00        33
           4       1.00      1.00      1.00        47
           5       1.00      1.00      1.00        49
           6       1.00      1.00      1.00        35
           7       1.00      1.00      1.00        34
           8       1.00      1.00      1.00        29
           9       1.00      1.00      1.00        39

    accuracy                           1.00       360
   macro avg       1.00      1.00      1.00       360
weighted avg       1.00      1.00      1.00       360

[[32  0  0  0  0  0  0  0  0  0]
 [ 0 29  0  0  0  0  0  0  0  0]
 [ 0  0 33  0  0  0  0  0  0  0]
 [ 0  

In [ ]:
dtc = DecisionTreeClassifier()
get_metrics(x_train,y_train,x_test,y_pred,"Decision Tree",dtc)

Model Name: Decision Tree
**************************************************
Testing Score: 0.8638888888888889
Training Score: 1.0
Accuracy Score: 1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        32
           1       1.00      1.00      1.00        29
           2       1.00      1.00      1.00        33
           3       1.00      1.00      1.00        33
           4       1.00      1.00      1.00        47
           5       1.00      1.00      1.00        49
           6       1.00      1.00      1.00        35
           7       1.00      1.00      1.00        34
           8       1.00      1.00      1.00        29
           9       1.00      1.00      1.00        39

    accuracy                           1.00       360
   macro avg       1.00      1.00      1.00       360
weighted avg       1.00      1.00      1.00       360

[[32  0  0  0  0  0  0  0  0  0]
 [ 0 29  0  0  0  0  0  0  0  0]
 [ 0  0 33  0  0  0  0  

In [ ]:
knc = KNeighborsClassifier()
get_metrics(x_train,y_train,x_test,y_pred,"KNN",knc)

Model Name: KNN
**************************************************
Testing Score: 0.9833333333333333
Training Score: 0.9895615866388309
Accuracy Score: 1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        32
           1       1.00      1.00      1.00        29
           2       1.00      1.00      1.00        33
           3       1.00      1.00      1.00        33
           4       1.00      1.00      1.00        47
           5       1.00      1.00      1.00        49
           6       1.00      1.00      1.00        35
           7       1.00      1.00      1.00        34
           8       1.00      1.00      1.00        29
           9       1.00      1.00      1.00        39

    accuracy                           1.00       360
   macro avg       1.00      1.00      1.00       360
weighted avg       1.00      1.00      1.00       360

[[32  0  0  0  0  0  0  0  0  0]
 [ 0 29  0  0  0  0  0  0  0  0]
 [ 0  0 33  0  0  0

In [ ]:
lr = LogisticRegression()
# Scale the data
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)
get_metrics(x_train_scaled,y_train,x_test_scaled,y_pred,"Logistic Regression",lr)

Model Name: Logistic Regression
**************************************************
Testing Score: 0.975
Training Score: 0.9986082115518441
Accuracy Score: 0.35
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        32
           1       0.33      0.66      0.44        29
           2       0.50      0.03      0.06        33
           3       0.52      0.39      0.45        33
           4       0.55      0.13      0.21        47
           5       0.30      0.88      0.45        49
           6       0.00      0.00      0.00        35
           7       0.28      0.85      0.43        34
           8       0.00      0.00      0.00        29
           9       0.79      0.38      0.52        39

    accuracy                           0.35       360
   macro avg       0.33      0.33      0.25       360
weighted avg       0.34      0.35      0.27       360

[[ 0  0  0  0  5 15  0 10  0  2]
 [ 0 19  0  3  0  4  0  2  0  1]
 [ 0  7  1  2  

/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
